foreground                #FFFFFF
background                #330F32
background_opacity        1.0
cursor                    #EDB8CB
cursor_text_color         #070807

active_tab_foreground     #330F32
active_tab_background     #D64858
inactive_tab_foreground   #D64858
inactive_tab_background   #330F32

selection_foreground      #330F32
selection_background      #FFFFFF

active_border_color       #330F32
inactive_border_color     #FFFFFF

# black
color0      #522950
color8      #8F578D

# red
color1      #FFCCDE
color9      #F0AAC3

# green
color2      #CCD1FF
color10     #AAB1F0

# yellow
color3      #FFCCD2
color11     #F0AAB2

# blue
color4      #E69AE3
color12     #E69AE3

# magenta
color5      #9AA1E6
color13     #9AA1E6

# cyan
color6      #E69AA2
color14     #E69AA2

# white
color7      #FFCCDE
color15     #F0AAC3

