# ─────────────────────────────────────
# SOURCING
# ─────────────────────────────────────
include ./theme.conf

# ─────────────────────────────────────
# SHELL
# ─────────────────────────────────────
shell fish
font_family      CaskaydiaCove Nerd Font Mono
font_size 9
bold_font auto
italic_font auto
bold_italic_font auto
confirm_os_window_close 0
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
tab_bar_style fade
tab_fade 1
active_tab_font_style bold
inactive_tab_font_style bold

# ─────────────────────────────────────
# CURSOR
# ─────────────────────────────────────
cursor_shape beam
cursor_trail 2
cursor_blink_interval 0

# ─────────────────────────────────────
# MARGINE
# ─────────────────────────────────────
window_padding_width 25

