[urgency_low]
    background = "#A3656C80"
    foreground = "#FFCCD2E6"
    frame_color = "#A3656C03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A3E6B80"
    foreground = "#CCD1FFE6"
    frame_color = "#3A3E6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
