# ─────────────────────────────────────
# GENERAL
# ─────────────────────────────────────
general {
  resize_on_border = true
  no_focus_fallback = true
  allow_tearing = true
  layout = dwindle

  snap {
    enabled = true
    window_gap = 4
    monitor_gap = 6
    respect_gaps = true
  }
}

# ─────────────────────────────────────
# DECORATION
# ─────────────────────────────────────
decoration {
	active_opacity = 0.90
	inactive_opacity = 0.75
	fullscreen_opacity = 1
	dim_strength = 0.1
	dim_special = 0.3

	blur {
    special = true
    brightness = 1
    noise = 0.04
    contrast = 1
    popups = true
    popups_ignorealpha = 0.6
    input_methods = true
    input_methods_ignorealpha = 0.8
	}
}

# ─────────────────────────────────────
# LAYOUT-ENV
# ─────────────────────────────────────
dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
	pseudotile = yes
}

master {
	new_status = master
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	vfr = false
	vrr = 0
	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
	animate_manual_resizes = false
	animate_mouse_windowdragging = true
	# enable_swallow = false
	# swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
	focus_on_activate = true
	on_focus_under_fullscreen = 1
	force_default_wallpaper = 0
	anr_missed_pings = 5
	allow_session_lock_restore = true
}


# ─────────────────────────────────────
# XWAYLAND
# ─────────────────────────────────────

xwayland {
	force_zero_scaling = true
}

# ─────────────────────────────────────
# INPUT
# ─────────────────────────────────────

input {
	kb_layout = us
	numlock_by_default = true
	repeat_delay = 300
	repeat_rate = 35

	follow_mouse = 1
	# force_no_accel = 0
	off_window_axis_events = 2
	
	sensitivity = 0

	# accel_profile = flat
	touchpad {
		natural_scroll = true
  	disable_while_typing = true
    clickfinger_behavior = true
    scroll_factor = 0.5

	}
}

device {
	name = epic-mouse-v1
	sensitivity = -0.5
}

gesture = 3, swipe, move,
gesture = 4, horizontal, workspace
gesture = 4, pinch, float
gestures {
	workspace_swipe_distance = 700
	workspace_swipe_cancel_ratio = 0.2
	workspace_swipe_direction_lock = true
	workspace_swipe_direction_lock_threshold = 10
	workspace_swipe_create_new = true
}

# ─────────────────────────────────────
# ECOSYSTEM
# ─────────────────────────────────────

ecosystem {
	# no_update_news = true
}

