# ─────────────────────────────────────
# EXEC
# ─────────────────────────────────────
exec-once = waybar
exec-once = awww-daemon
exec-once = dunst
exec-once = hypridle
exec-once = ~/.local/bin/exec-start.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/lib/xdg-desktop-portal-gtk
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = udiskie -t
exec-once = nm-applet --indicator

# ─────────────────────────────────────
# CLIPBOARD-MANAGER
# ─────────────────────────────────────
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard primary

