# ─────────────────────────────────────
# GENERAL
# ─────────────────────────────────────
general {
  resize_on_border = true
  no_focus_fallback = true
  allow_tearing = true
  layout = dwindle

  snap {
    enabled = true
    window_gap = 4
    monitor_gap = 6
    respect_gaps = true
  }
}

# ─────────────────────────────────────
# DECORATION
# ─────────────────────────────────────
decoration {
	active_opacity = 0.90
	inactive_opacity = 0.75
	fullscreen_opacity = 1
	dim_strength = 0.1
	dim_special = 0.3

	blur {
    special = true
    brightness = 1
    noise = 0.04
    contrast = 1
    popups = true
    popups_ignorealpha = 0.6
    input_methods = true
    input_methods_ignorealpha = 0.8
	}
}

# ─────────────────────────────────────
# LAYOUT-ENV
# ─────────────────────────────────────
dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
	pseudotile = yes
}

master {
	new_status = master
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	vfr = false
	vrr = 0
	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
	animate_manual_resizes = false
	animate_mouse_windowdragging = true
	focus_on_activate = true
	on_focus_under_fullscreen = 1
	force_default_wallpaper = 0
	anr_missed_pings = 5
	allow_session_lock_restore = true
}

# ─────────────────────────────────────
# XWAYLAND
# ─────────────────────────────────────

xwayland {
	force_zero_scaling = true
}



