#? Below is a fallback setup to ensure VYLE do not fail no matter what.
#? Ensures stability and we will warn the user.
#? Rerunning the installation might be needed.
#? NOTE: They may never get executed. Extremely rare case.

# hyprlang if !TERMINAL
$TERMINAL = kitty
$VYLE_VAR_UNINITIALIZED = TERMINAL
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif

# hyprlang if !EDITOR
$EDITOR = vscodium
$VYLE_VAR_UNINITIALIZED = EDITOR
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif

# hyprlang if !EXPLORER
$EXPLORER = dolphin
$VYLE_VAR_UNINITIALIZED = EXPLORER
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif

# hyprlang if !BROWSER
$BROWSER = firefox
$VYLE_VAR_UNINITIALIZED = BROWSER
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif

# hyprlang if !LOCKSCREEN
$LOCKSCREEN = hyprlock 
$VYLE_VAR_UNINITIALIZED = LOCKSCREEN
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif

# hyprlang if !CURSOR
$CURSOR = Bibata-Modern-Ice
$VYLE_VAR_UNINITIALIZED = CURSOR
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif

# hyprlang if !CURSOR_SIZE
$CURSOR_SIZE = 24
$VYLE_VAR_UNINITIALIZED = CURSOR_SIZE
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif 

# hyprlang if !FONT_NAME
$FONT_NAME = CaskaydiaCove Nerd Font Mono 
$VYLE_VAR_UNINITIALIZED = FONT_NAME
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif 

# hyprlang if !FONT_ANTIALIASING 
$FONT_ANTIALIASING = rgba 
$VYLE_VAR_UNINITIALIZED = FONT_ANTIALIASING
$VYLE_WARNING_INITIALIZE = 1 
# hyprlang endif 

# hyprlang if !FONT_HINTING 
$FONT_HINTING = slight 
$VYLE_VAR_UNINITIALIZED = FONT_HINTING
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif

# hyprlang if !FONT_SIZE 
$FONT_SIZE = 10.5
$VYLE_VAR_UNINITIALIZED = FONT_SIZE
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif 

# hyprlang if !DOCUMENT_FONT
$DOCUMENT_FONT = JetBrainsMono Nerd Font 
$VYLE_VAR_UNINITIALIZED = DOCUMENT_FONT 
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif 

# hyprlang if !DOCUMENT_FONT_SIZE
$DOCUMENT_FONT_SIZE = 10
$VYLE_VAR_UNINITIALIZED = DOCUMENT_FONT_SIZE
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif 

# hyprlang if !MONOSPACE_FONT 
$MONOSPACE_FONT = CaskaydiaCove Nerd Font Mono
$VYLE_VAR_UNINITIALIZED = MONOSPACE_FONT
$VYLE_WARNING_INITIALIZE = 1
# hyprlang endif 

# hyprlang if !MONOSPACE_FONT_SIZE
$MONOSPACE_FONT_SIZE = 10
$VYLE_VAR_UNINITIALIZED = MONOSPACE_FONT_SIZE 
$VYLE_WARNING_INITIALIZE = 1 
# hyprlang endif 


#! --- Notify user if above vars are empty ---

# hyprlang if VYLE_WARNING_INITIALIZE
exec = hyprctl notify 0 15000 0 "[Warning]: $VYLE_VAR_UNINITIALIZED is found empty and has fallen to pitfall:safety. Is Vyle initialized!?"
# hyprlang endif
