# // ██████╗░░█████╗░  ███╗░░██╗░█████╗░████████╗  ███████╗██████╗░██╗████████╗
# // ██╔══██╗██╔══██╗  ████╗░██║██╔══██╗╚══██╔══╝  ██╔════╝██╔══██╗██║╚══██╔══╝
# // ██║░░██║██║░░██║  ██╔██╗██║██║░░██║░░░██║░░░  █████╗░░██║░░██║██║░░░██║░░░
# // ██║░░██║██║░░██║  ██║╚████║██║░░██║░░░██║░░░  ██╔══╝░░██║░░██║██║░░░██║░░░
# // ██████╔╝╚█████╔╝  ██║░╚███║╚█████╔╝░░░██║░░░  ███████╗██████╔╝██║░░░██║░░░
# // ╚═════╝░░╚════╝░  ╚═╝░░╚══╝░╚════╝░░░░╚═╝░░░  ╚══════╝╚═════╝░╚═╝░░░╚═╝░░░


#? Define $LIB_DIR at the first header! 
#? We are going to wrap variables.conf to tmq.write.sh
$LIB_DIR = $HOME/.local/lib/vyle

#? Variables
source = ./variables.conf

#? Migration handling
source = ./migration.conf

#? Default values
source = ./defaults.conf

#? Window rules
source = ./windowrules.conf

#? Environment Variable Setup
source = ./env.conf

#? Dynamic Themeing stuff and execution handling. 
source = ./dynamic.conf

#? Vyle's startup overridable.
source = ./startup.conf

