#? Variables
source = ./variables.conf

#? Migration handling
source = ./migration.conf

#? Default Values: Vyle Defaults
source = ./defaults.conf

#? Window rules
source = ./windowrules.conf

#? Environment variable setup
source = ./env.conf

#? Dynamic Stuff example theming and variable handlings
source = ./dynamic.conf

# Vyle's startup overridable too!
source = ./startup.conf
