
# This is from Hyprland Wiki. Below is written for managing the environment of Hyprland.
# See hyprland wiki https://wiki.hypr.land/Configuring/Uncommon-tips--tricks/ for more information.

#? This part defines variables for version guards
#? Maintenance rules:
#? 1. For each Hyprland release, check for breaking changes and update blocks.
#? 2. One assignment block per version, oldest to newest.
#? 3. On breaking changes, remove incompatible variable assignments in that block.
#? 4. User rules: use '# hyprlang if CATEGORY_HYPRLAND_V_0_XX'.
#? 5. Old configs are moved to ~/.local/share/hyde/migrations/hypr/* for older versions.
#? 6. Only transitions are supported; old versions not guaranteed.

# In this case we added WINDOWRULES_HYPRLAND_V_0_53
# Where WINDOWRULES is the category, and 0_53 is the version number

#─────────────────────────────────────
# VARS
# ─────────────────────────────────────
# hyprlang if HYPRLAND_V_0_53
$WINDOWRULES_HYPRLAND_V_0_53 = 1# hyprlang endif

# hyprlang if HYPRLAND_V_0_54
$WINDOWRULES_HYPRLAND_V_0_54 = 1
$WINDOWRULES_HYPRLAND_V_0_53 = 1
# hyprlang endif

