$LIB_DIR=$HOME/.local/lib/vyle

$MOD = SUPER
$mainMod = $MOD

## DO NOT TOUCH THIS VARS! They essentially loads your configuration.
$TERMINAL = $(vyle -c -r CONSOLE)
$EDITOR = $(vyle -c -r EDITOR)
$EXPLORER = $(vyle -c -r EXPLORER)
$BROWSER = $(vyle -c -r BROWSER)
$LOCKSCREEN = $(vyle -c -r LOCK_SCREEN)
$TASKMANAGER = $(vyle -c -r TASK_MANAGER)
$CURSOR = $(vyle -c -r CURSOR_THEME)
$CURSOR_SIZE = $(vyle -c -r CURSOR_SIZE)

$FONT_NAME = $(vyle -c -r GTK_FONT_NAME)
$FONT_ANTIALIASING = $(vyle -c -r GTK_FONT_ANTIALIASING)
$FONT_HINTING = $(vyle -c -r FONT_HINTING)
$FONT_SIZE = $(vyle -c -r GTK_FONT_SIZE)
$DOCUMENT_FONT = $(vyle -c -r GTK_DOCUMENT_FONT)
$DOCUMENT_FONT_SIZE = $(vyle -c -r GTK_DOCUMENT_FONT_SIZE)
$MONOSPACE_FONT = $(vyle -c -r GTK_MONOSPACE_FONT)
$MONOSPACE_FONT_SIZE = $(vyle -c -r GTK_MONOSPACE_FONT_SIZE)

