## DO NOT TOUCH THIS VARS! They essentially loads your configuration.
## This file has been parsed by tmq.write.sh: wallbash
## If you are looking to edit this file -> /home/iris/.local/share/vyle/wallbash/variables.dcol 

$TERMINAL = kitty
$EDITOR = vscodium
$EXPLORER = dolphin
$BROWSER = firefox
$LOCKSCREEN = hyprlock
$TASKMANAGER = gnome-system-monitor
$CURSOR = Bibata-Modern-Ice
$CURSOR_SIZE = 18

$FONT_NAME = CaskaydiaCove Nerd Font Mono
$FONT_ANTIALIASING = rgba
$FONT_HINTING = slight
$FONT_SIZE = 10.5
$DOCUMENT_FONT = JetBrainsMono Nerd Font
$DOCUMENT_FONT_SIZE = 10
$MONOSPACE_FONT = CaskaydiaCove Nerd Font Mono
$MONOSPACE_FONT_SIZE = 20

