#!/usr/bin/env bash
VYLE_RESERVED_THEME="Catppuccin-Mocha"
VYLE_THEME="Wallbash-Ivy"
VYLE_WALLPAPER_DIRECTORY="/home/iris/.config/vyle/theme/Catppuccin-Mocha/wallpapers"
VYLE_CURRENT_IMAGE="${VYLE_CONFIG_HOME}/theme/${VYLE_RESERVED_THEME}/wallpapers/1_rain_world.png"
WALLBASH_MODE=0
