#* You can freelly edit this file, however, it is recommended to edit userprefs.conf!
#* All Files Below are yours to modify! <-- [FROM HYDE]

# ────────────────────────────────────────────────
#? This is only used for boilerplatting, do not touch them.
source = $HOME/.local/share/vyle/hypr/hyprland.conf
# ────────────────────────────────────────────────

source = ./keybindings.conf # Keyboard Shortcuts
source = ./windowrules.conf # Window Rules
source = ./monitors.conf # Monitor Configuration
source = ./userprefs.conf # Uesr preference // Edit this file to change your Hyprland configuration

