
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hypr.land/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hypr.land/Configuring/Variables/#input
input {
	kb_layout = us
	numlock_by_default = true
	repeat_delay = 300
	repeat_rate = 35

	follow_mouse = 1
	# force_no_accel = 0
	off_window_axis_events = 2
	
	sensitivity = 0

	# accel_profile = flat
  # 🔗 See https://wiki.hypr.land/Configuring/Variables/#touchpad
	touchpad {
		natural_scroll = true
  	disable_while_typing = true
    clickfinger_behavior = true
    scroll_factor = 0.5

	}
}

device {
	name = epic-mouse-v1
	sensitivity = -0.5
}

# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gesture = 3, swipe, move,
gesture = 4, horizontal, workspace
gesture = 4, pinch, float
gestures {
	workspace_swipe_distance = 700
	workspace_swipe_cancel_ratio = 0.2
	workspace_swipe_direction_lock = true
	workspace_swipe_direction_lock_threshold = 10
	workspace_swipe_create_new = true
}

# for window shallow similar to devour
misc {
  # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
  # enable_swallow = false
}
ecosystem {
	# no_update_news = true
}

