export VYLE_CONFIGURATION_PLACEHOLDER="ivy|wallbash" # Supported Placeholder of wallbash.
export VYLE_CONFIGURATION_SKIP_TEMPLATE=( )
export VYLE_CONFIGURATION_CORE=3
export WALLPAPER_CONFIGURATION_BACKEND="swww" # Current-Backend Set.
export WALLPAPER_CONFIGURATION_CUSTOMPATH=( )
export WALLPAPER_SWWW_FRAMERATE=60
export WALLPAPER_SWWW_TRANSITION_DURATION=0.4
export WALLPAPER_SWWW_TRANSITION_BEZIER=".43,1.19,.1,.4" # Transition Bezier.
export WALLPAPER_SWWW_ANIMATION="grow" # Transition Animation.
export WALLPAPER_SWWW_ANIMATION_PREVIOUS="outer" # Transition AnimationPrevious.
export WALLPAPER_SWWW_ANIMATION_NEXT="grow" # Transition AnimationNext.
export WALLPAPER_SWWW_ANIMATION_THEME="grow" # Transition AnimationTheme.
export ROFI_LAUNCH_FONT="JetBrainsMono Nerd Font" # Font for rofilauncher.sh
export ROFI_LAUNCH_SCALE=9
export ROFI_LAUNCH_STYLE=1
export ROFI_WALLPAPER_FONT="JetBrainsMono Nerd Font" # Font for wbselecgen.sh
export ROFI_WALLPAPER_SCALE=9
export ROFI_WALLPAPER_COLUMN=4
export ROFI_THEME_FONT="JetBrainsMono Nerd Font" # Font for themeswitch.sh
export ROFI_THEME_SCALE=9
export ROFI_THEME_COLUMN=2
export ROFI_THEME_STYLE=2
export ROFI_WALLBASH_FONT="JetBrainsMono Nerd Font" # Font for wallbashtoggle.sh
export ROFI_WALLBASH_SCALE=9
export ROFI_SWITCH_SCALE=12
export WLOGOUT_STYLE=2
export FASTFETCH_FETCHICON="${XDG_CONFIG_HOME}/fastfetch/icons" # Fetches Directory for fastfetch.sh
export BRIGHTNESS_CONFIGURATION_FETCHICON="${XDG_CONFIG_HOME}/dunst/icons/vol" # Fetches Directory for brightnesscontrol.sh
export BRIGHTNESS_CONFIGURATION_STEPS=5
export BRIGHTNESS_CONFIGURATION_NOTIFY_MUTE=0
export VOLUME_CONFIGURATION_FETCHICON="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/icons/vol" # Fetches Directory for voluemcontrol.sh
export VOLUME_CONFIGURATION_STEPS=5
export VOLUME_CONFIGURATION_STEPS_MUTE=0
export VOLUME_CONFIGURATION_NOTIFY_MUTE=0
export NOTIFICATION_CONFIGURATION_FONT="mononoki Nerd Font Bold" # Font Configuration for Dunst.
export NOTIFICATION_CONFIGURATION_FONT_SIZE=10
export HYPRLAND_CONFIGURATION_TERMINAL="kitty" # Terminal
export HYPRLAND_CONFIGURATION_EDITOR="vscodium" # Editor
export HYPRLAND_CONFIGURATION_EXPLORER="dolphin" # Explorer
export HYPRLAND_CONFIGURATION_BROWSER="firefox" # Browser
export HYPRLAND_CONFIGURATION_LOCK_SCREEN="hyprlock" # LockScreen
export HYPRLAND_CONFIGURATION_TASK_MANAGER="gnome-system-monitor" # TaskManager
export HYPRLAND_CONFIGURATION_CURSOR="Bibata-Modern-Ice" # Cursor Theme
export HYPRLAND_CONFIGURATION_CURSOR_SIZE=20
export GTK_CONFIGURATION_FONT="CaskaydiaCove Nerd Font Mono" # Font Name
export GTK_CONFIGURATION_FONT_ANTIALIASING="rgba" # Font Antialiasing
export GTK_CONFIGURATION_FONT_HINTING="slight" # Font Hinting
export GTK_CONFIGURATION_FONT_SIZE=10.5
export GTK_CONFIGURATION_DOCUMENT_FONT="JetBrainsMono Nerd Font" # Document Font
export GTK_CONFIGURATION_DOCUMENT_FONT_SIZE=10
export GTK_CONFIGURATION_MONOSPACE_FONT="CaskaydiaCove Nerd Font Mono" # Monospace Font
export GTK_CONFIGURATION_MONOSPACE_FONT_SIZE=10
