#  █░█ █▄█ █░░ █▀▀ 
#  ▀▄▀ ░█░ █▄▄ ██▄  
# Vyle configuration.
[Vyle.Configuration]
PlaceHolder = "ivy|wallbash" # Supported Placeholder of wallbash.
Skip_Template = [] # Templates to Skip when using wallbash.
Core = 3 # Limit usage of wallbash cores. NOTE: Use "$(nproc)" if you want to maximize full usage.

# █░█░█ ▄▀█ █░░ █░░ █▀█ ▄▀█ █▀█ █▀▀ █▀█
# ▀▄▀▄▀ █▀█ █▄▄ █▄▄ █▀▀ █▀█ █▀▀ ██▄ █▀▄
# Wallpaper configuration.
[Wallpaper.Configuration]
Backend = "swww" # Current-Backend Set.
CustomPath = [] # List of paths to search for wallpapers.

# wbselecgen.sh configuration.
[Wallpaper.Swww]
Framerate = 60 # Transition Framerate.
Transition_Duration = 0.5 # Transition Duration.
Transition_Bezier = ".43,1.19,.1,.4" # Transition Bezier.
Animation = "grow" # Transition Animation.
Animation_Previous = "outer" # Transition AnimationPrevious.
Animation_Next = "grow" # Transition AnimationNext.
Animation_Theme = "grow" # Transition AnimationTheme.

# █▀█ █▀█ █▀▀ █
# █▀▄ █▄█ █▀░ █
# rofilauncher.sh configuration.
[Rofi.Launch]
Font = "JetBrainsMono Nerd Font" # Font for rofilauncher.sh
Scale = 9 # Scale for rofilauncher.sh
Style = 1

# wbselecgen.sh configuration.
[Rofi.Wallpaper]
Font = "JetBrainsMono Nerd Font" # Font for wbselecgen.sh
Scale = 9 # Scale for wbselecgen.sh
Column = 4 # Column for wbselecgen.sh

# themeswitch.sh configuration.
[Rofi.Theme]
Font = "JetBrainsMono Nerd Font" # Font for themeswitch.sh
Scale = 9 # Scale for themeswitch.sh
Column = 2 # Column for themeswitch.sh
Style = 2 # Style for themeswitch.sh

# wallbashtoggle.sh configuraiton
[Rofi.Wallbash]
Font = "JetBrainsMono Nerd Font" # Font for wallbashtoggle.sh
Scale = 9 # Scale for wallbashtoggle.sh

# style-launcher.sh configuration.
[Rofi.Switch]
Scale = 12 # Scale for style-launcher.sh

# █░░ █▀█ █▀▀ █▀█ █░█ ▀█▀
# █▄▄ █▄█ █▄█ █▄█ █▄█ ░█░
# logoutlaunch.sh configuration.
[Wlogout]
Style = 2 # Style for logoutlauncher.sh | Picks up style for wlogout!

# █▀▀ ▄▀█ █▀ ▀█▀ █▀▀ █▀▀ ▀█▀ █▀▀ █░█
# █▀░ █▀█ ▄█ ░█░ █▀░ ██▄ ░█░ █▄▄ █▀█
# fastfetch.sh configuration.
[Fastfetch]
FetchIcon = "${XDG_CONFIG_HOME}/fastfetch/icons" # Fetches Directory for fastfetch.sh

# █▄▄ █▀█ █ █▀  █░█ ▀█▀ █▄░█ █▀▀ █▀ █▀ █▀ ▀█▀ █░░ 
# █▄█ █▀▄ █ █▄█ █▀█ ░█░ █░▀█ ██▄ ▄█ ▄█ █▄ ░█░ █▄▄
# brightnesscontrol.sh configuration
[Brightness.Configuration]
FetchIcon = "${XDG_CONFIG_HOME}/dunst/icons/vol" # Fetches Directory for brightnesscontrol.sh
Steps = 5 # Steps Taken for brightnesscontrol.sh
Notify_Mute = 0 # Mute: 0 = False; 1 = True

# █░█ █▀█ █░░ █░█ █▀▄▀█ █▀▀ █▀ ▀█▀ █░░ 
# ▀▄▀ █▄█ █▄▄ █▄█ █░▀░█ ██▄ █▄ ░█░ █▄▄
# volumecontrol.sh configuration.
[Volume.Configuration]
FetchIcon = "${XDG_CONFIG_HOME:-$HOME/.config}/dunst/icons/vol" # Fetches Directory for voluemcontrol.sh
Steps = 5 # Steps Taken for volumecontrol.sh
Steps_Mute = 0 # Silent Popups from step-taken. Mute: 0 = False; 1 = True
Notify_Mute = 0 # Silent Popups of Mic/Speaker. Mute: 0 = False; 1 = True

# █▄░█ █▀█ ▀█▀ █ █▀▀ █ █▀▀ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █░▀█ █▄█ ░█░ █ █▀░ █ █▄▄ █▀█ ░█░ █ █▄█ █░▀█
# dunstctl configuration
[Notification.Configuration]
Font = "mononoki Nerd Font Bold" # Font Configuration for Dunst. 
Font_Size = 10 # Font_Size for Dunst

# █░█ █▄█ █▀█ █▀█ █░░ ▄▀█ █▄░█ █▀▄
# █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▀█ █░▀█ █▄▀
# Hyprland Configuration.
[Hyprland.Configuration]
Terminal = "kitty" # Terminal
Editor = "vscodium" # Editor
Explorer = "dolphin" # Explorer
Browser = "firefox" # Browser
Lock_Screen = "hyprlock" # LockScreen
Task_Manager = "gnome-system-monitor" # TaskManager
Cursor = "Bibata-Modern-Ice" # Cursor Theme
Cursor_Size = 20 # Cursor Size

# █▀▀ ▀█▀ █▄▀
# █▄█ ░█░ █░█
# GTK Configuration
[GTK.Configuration]
Font = "CaskaydiaCove Nerd Font Mono Regular" # Font Name
Font_Antialiasing = "rgba" # Font Antialiasing
Font_Hinting = "slight" # Font Hinting
Font_Size = 10.5 # Font Size
Document_Font = "CaskaydiaCove Nerd Font Mono Semi-Bold" # Document Font
Document_Font_Size = 10 # Document Font Size
Monospace_Font = "CaskaydiaCove Nerd Font Mono Semi-Bold" # Monospace Font
Monospace_Font_Size = 10 # Monospace Font Size

