export VYLE_CONFIGURATION_CORE=$(nproc)
export VYLE_CONFIGURATION_SKIP_TEMPLATE=( )
export WALLPAPER_CONFIGURATION_BACKEND="awww" # Current-Backend Set.
export WALLPAPER_CONFIGURATION_CUSTOMPATH=( )
export WALLPAPER_SWWW_FRAMERATE=60
export WALLPAPER_SWWW_TRANSITION_DURATION=0.5
export WALLPAPER_SWWW_TRANSITION_BEZIER=".43,1.19,.1,.4" # Transition Bezier.
export WALLPAPER_SWWW_ANIMATION_PREVIOUS="outer" # Transition AnimationPrevious.
export WALLPAPER_SWWW_ANIMATION_NEXT="grow" # Transition AnimationNext.
export WALLPAPER_SWWW_ANIMATION_THEME="grow" # Transition AnimationTheme.
export WALLPAPER_SWWW_ARGS=( )
export ROFI_LAUNCH_FONT="JetBrainsMono Nerd Font" # Font for rofilauncher.sh
export ROFI_LAUNCH_STYLE=1
export ROFI_WALLPAPER_FONT="JetBrainsMono Nerd Font" # Font for wbselecgen.sh
export ROFI_THEME_FONT="JetBrainsMono Nerd Font" # Font for themeswitch.sh
export WLOGOUT_STYLE=1
export FASTFETCH_FETCHICON="${XDG_CONFIG_HOME}/fastfetch/icons" # Fetches Directory for fastfetch.sh
export BRIGHTNESS_FETCHICON="${XDG_CONFIG_HOME}/dunst/icons/vol" # Fetches Directory for brightnesscontrol.sh
export BRIGHTNESS_STEPS=5
export BRIGHTNESS_NOTIFY_MUTE=0
export VOLUME_FETCHICON="$BRIGHTNESS_FETCHICON" # Fetches Directory for voluemcontrol.sh
export VOLUME_STEPS=5
export VOLUME_STEPS_MUTE=0
export VOLUME_NOTIFY_MUTE=0
export NOTIFICATION_FONT_NAME="Mononoki Nerd Font Bold" # Font Configuration for Dunst.
export NOTIFICATION_FONT_SIZE=10
export HYPRLAND_TERMINAL="kitty" # Terminal
export HYPRLAND_EDITOR="vscodium" # Editor
export HYPRLAND_EXPLORER="dolphin" # Explorer
export HYPRLAND_BROWSER="firefox" # Browser
export HYPRLAND_LOCK_SCREEN="hyprlock" # LockScreen
export HYPRLAND_TASK_MANAGER="gnome-system-monitor" # TaskManager
export HYPRLAND_CURSOR_THEME="Bibata-Modern-Ice" # Cursor Theme
export HYPRLAND_CURSOR_SIZE=24
export GTK_THEME="Wallbash-Gtk"
export GTK_FONT_NAME="CaskaydiaCove Nerd Font Mono" # Font Name
export GTK_FONT_ANTIALIASING="rgba" # Font Antialiasing
export GTK_FONT_HINTING="slight" # Font Hinting
export GTK_FONT_SIZE=10.5
export GTK_DOCUMENT_FONT="JetBrainsMono Nerd Font" # Document Font
export GTK_DOCUMENT_FONT_SIZE=10
export GTK_MONOSPACE_FONT="CaskaydiaCove Nerd Font Mono" # Monospace Font
export GTK_MONOSPACE_FONT_SIZE=20
