# ─────────────────────────────────────
# EXEC
# ─────────────────────────────────────

$GTK_THEME="adw-gtk3-dark"
$ICON_THEME=Tela-circle-dracula

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'
execr = gsettings set org.gnome.desktop.interface font-name "$FONT_NAME $FONT_SIZE"
execr = gsettings set org.gnome.destop.interface font-antialiasing "$FONT_ANTIALIASING"
execr = gsettings set org.gnome.desktop.interface font-hinting "$FONT_HINTING"
execr = gsettings set org.gnome.desktop.interface monospace-font-name "$MONOSPACE_FONT $MONOSPACE_FONT_SIZE"
execr = gsettings set org.gnome.desktop.interface document-font-name "$DOCUMENT_FONT $DOCUMENT_FONT_SIZE"
execr = gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR"
execr = gsettings set org.gnome.desktop.interface cursor-size "$CURSOR_SIZE"
exec = hyprctl setcursor $CURSOR $CURSOR_SIZE

