
#//---ivy mode enabled---
# Overriding the values below - DO NOT OVERWRITE --- # IF YOU DO, THEN EDIT $(confDir)/ivy-shell/shell/hypr.ivy-- #
general {
    col.active_border = rgba(EDB8CBff) rgba(522937ff) 45deg
    col.inactive_border = rgba(330F32ff) rgba(6770C9ff) 45deg
}

group {
    col.border_active = rgba(EDB8CBff) rgba(522937ff) 45deg
    col.border_inactive = rgba(330F32cc) rgba(6770C9cc) 45deg
    col.border_locked_active = rgba(D0D5D5ff) rgba(070807ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(C5C4BFcc) 45deg
}

decoration {
    shadow:color = rgba(330F32cc)
}

#//---------------------------