
$text_color = rgba(FFFFFFFF)
$entry_background_color = rgba(330F3211)
$entry_border_color = rgba(EDB8CB55)
$entry_color = rgba(FFFFFFFF)
$font_family = JetBrainsMono Nerd Font Medium
$font_family_clock = JetBrainsMono Nerd Font Medium
$font_material_symbols = JetBrainsMono Nerd Font Medium