
$text_color = rgba(FFFFFFFF)
$entry_background_color = rgba(1B1B2911)
$entry_border_color = rgba(974C4E55)
$entry_color = rgba(FFFFFFFF)
$font_family = JetBrainsMono Nerd Font Medium
$font_family_clock = JetBrainsMono Nerd Font Medium
$font_material_symbols = JetBrainsMono Nerd Font Medium
$hyprlock_background = $XDG_CONFIG_HOME/vyle/theme/Catppuccin-Mocha/wallpapers/1_rain_world.png
